project:
  type: book
  output-dir: docs


book:
  title: "Introduction to R for Economists"
  author: "Priyanga Dilini Talagala"
  date: "1/6/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

