project:
  type: book
  output-dir: docs


book:
  title: "Getting Started with R for Economists"
  author: "Priyanga Dilini Talagala"
  date: "1/6/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - rbasics.qmd
    - quarto.qmd
    - dataload.qmd
    - quarto.qmd
    - datawrangling.qmd
    - dataviz.qmd
    - statmodelling.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

